### ISSUE TITLE
Want a "type" setting for volume host path

### ISSUE THREAD

**Issue by fuzhibo** [fuzhibo/drone-runner-kube#1]
In pipeline, we use "volumes" to set volumes with different type. However, type `host`dose not support "type" config for volume host path type. In kubernetes, volume of hostPath has a field "type" to support different use case https://kubernetes.io/docs/concepts/storage/volumes/#hostpath.  
Currently, the code in runner was only support `DirectoryOrCreate` type, it hard to use when use in pipeline.

**Comment by fuzhibo** [comment]
The new settings will be like following:
```yaml
- name: cache
  host:
    path: /var/lib/cache
    type: DirectoryOrCreate
```
